name: Deploy artifact for CMS core

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Setting up Java
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1
      - name: Publishing package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


